# Generated by Django 6.0.3 on 2026-03-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
